### ISSUE TITLE
From experience, the event header marker is not sufficient to identify event header

### ISSUE THREAD

**Issue by relleums** [fact-project/pycorsikaio#1]
I have experienced that checking for the event header marker b'EVTH' is not sufficient to identify event header. I had this quiet often that photon blocks by accident started with b'EVTH'. To decrease the risk for false positive matches, I added a check on the run number. I check that both the event header run number and the run header run number are the same.

https://github.com/fact-project/pycorsikaio/blob/a988423579c00c4b7318960768d019e364263500/corsikaio/io.py#L70

I added a run number check:

https://github.com/fact-project/photon_stream/blob/81cf3b0d925ca370cc70ff92973641d7f1d23c8e/photon_stream/simulation_truth/corsika_headers.py#L42

**Comment by MaxNoe** [comment]
This seems to be correct:

For a file with 1500 showers, I counted the occurences of `b'EVTH'` and `b'EVTE'`:
```
In [9]: len(event_headers)
Out[9]: 1506

In [10]: len(event_end)
Out[10]: 1500
```
